<?php 
$customtabenable 		= 		Mage::getStoreConfig('avejanasetting/avejanaconfiguration/customtab');
$avejanamodule 			= 		Mage::getStoreConfig('avejanasetting/avejanaconfiguration/active');
if(($customtabenable==1) && ($avejanamodule==1)){  //check if custom tab is enabled ?>
<div id="avejana-tabs" class="avejana-tabs">
    <ul class="avejana-tab-links">
        <li class="custab reviewclick first active"><span href="#avejana-tab1">Reviews</span></li>
        <li class="custab qaclick"><span href="#avejana-tab2">Q&amp;A</span></li>
    </ul>

    <div class="avejana-avejana-tab-content">
        <div id="avejana-tab1" class="avejana-tab active">
            <?php echo $this->getLayout()->createBlock('avejanarms/index')->setTemplate('avejanarms/review.phtml')->toHtml(); ?>
        </div>

        <div id="avejana-tab2" class="avejana-tab">
            <?php echo $this->getLayout()->createBlock('avejanarms/index')->setTemplate('avejanarms/qa.phtml')->toHtml(); ?>
        </div>

    </div>
</div>

<script>
	jQuery(document).ready(function() {
		jQuery('.avejana-tabs .avejana-tab-links span').on('click', function(e)  {
			var currentAttrValue = jQuery(this).attr('href');

			// Show/Hide avejana-tabs
			jQuery('.avejana-tabs ' + currentAttrValue).show().siblings().hide();

			// Change/remove current avejana-tab to active
			jQuery(this).parent('li').addClass('active').siblings().removeClass('active');

			e.preventDefault();
		});
		
		jQuery(document).on('click',".qaformopen", function(event){
			jQuery(".qaclick span").click();
			
			jQuery('html, body').animate({
					scrollTop: jQuery(".avejana-tabs").offset().top-100
			}, 1000);
		});
		
		jQuery(document).on('click',".reviewformopen", function(event){
		
			jQuery(".reviewclick span").click();
			jQuery('html, body').animate({
					scrollTop: jQuery(".avejana-tabs").offset().top-100
			}, 1000);
		
  	 });
	
	});
</script>

<?php } ?>