
<?php		$moduledir=Mage::getModuleDir('controllers', 'Avejana_AvejanaRMS');
			include_once($moduledir.'/PageLister.php');
			$avejanareviewes	= 	$this->getAvejanaReviesListing(Mage::getSingleton('core/session')->getProID());

			if(count($avejanareviewes)>0){
				$currentPage 		= !empty($_GET['page']) ? (int) $_GET['page'] : 1;
 				$allItems 			= array();
				$totalreviewcount 	= count($avejanareviewes);
				//print_r($avejanareviewes);
				//die;
				foreach($avejanareviewes as $_review){
				$first_letter = substr($_review->UserName, 0, 1);
					$ratingpercentage=  $_review->Ratings*20;
					$replysction = $_review->Reply != "" ? 
									'<div class="avejana-responce">
										<p class="avejana-header">
											<i class="fa fa-comment"></i>&nbsp;<span>'.$_review->RepliedBy.'</span> 
											Response :
										</p>
										<div class="response">
											<p class="detail">'.$_review->Reply.'</p>
										</div>
									</div>' : '';
					$allItems[]= '
					<div class="avejanahoriline"><hr style="width: 100%;"></div>
						<div class="avejana-review-feld">
							<div class="avejana-initial" >
								<a href="javascript:void(0)">
									<span class="first-letter">'.ucfirst($first_letter).'</span>
								</a>
							</div>
							<div class="avejana-feed"><div class="avejana-initial2" >
								<strong><a href="javascript:void(0)" class="text-muted">'.$_review->UserName.'</a></strong>&nbsp;<small class="text-muted">'.$this->formatDate($_review->ReviewDate).'</small>
								<div class=" avejana-small-star">
									<div id="review_rate" class="display_rate avejana-container"  readonly="readonly">

										<div class="stars star-ratings-sprite"><span style="width:'.$ratingpercentage.'%" class="star-ratings-sprite-rating"></span></div>

									</div>
								</div>
								<div class="reviewtitle" >
									<a href="javascript:void(0)">'.$_review->Title.'</a>
								</div>
								<div class="avejana-tweet">
									<p style="color: #333;">'.$review_destails = nl2br($_review->Description).'</p>
								</div>'.$replysction.'</div>
						</div>
				  </div>';?>
				<?php } 
				/*************Pagination Code**************/
				$pl = new PageLister($allItems, $currentPage);
				//print_r($pl);die;
				 $pageList = $pl->makePageList();
				//print_r($pageList);
				$currentItems = $pl->getCurrentItems();
				//print_r($currentItems);die;
				$itemcount = count($currentItems);
				/**
				 * Finally output the current page items and the pagelist
				 */

				

				foreach ($currentItems as $item)
				{
				  echo "$item <br />\n";
				}
				
				if($totalreviewcount>10){
					echo "Pages: \n";

					foreach ($pageList as $page)
					{
						// make sure only valid urls are clickable (prev page at page 1 won't yield a valid previous next page)
						if ($page['url']) {
						  echo "<a href='?page={$page['page']}'>{$page['label']}</a> ";
						}
						else {
						  echo $page['label'].' ';
						}
					}		
				}
				
				
				}	?>
		