<a id="qa-tab-open" name="question-form"></a>
<?php 	$current_product 	=  Mage::registry('current_product');?>
<div class="av-page-title">
    <a href="javascript:void(0)" class="qatitle"><?php echo Mage::helper('avejanarms')->__('Ask a Question') ?></a>
</div>
<div class="qaformarea avejana-content">
<form action="<?php echo $this->getUrl('avejanarms/qa/qapost'); ?>" id="avejanaqa" method="post" class="scaffold-form">
    <div class="fieldarea">
        
        <ul class="av-form-list">
			<input type="hidden" name="product_id" value="<?php echo $current_product->getId();?>"/> 
			
			<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) {
 
					// Load the customer's data
					$customer = Mage::getSingleton('customer/session')->getCustomer();
					echo '<input name="name" id="name" value="'.$customer->getName().'" class="input-text required-entry" type="hidden" />';

					echo '<input name="email" id="email" value="'.$customer->getEmail().'" class="input-text required-entry validate-email" type="hidden"  />';


				}else{ ?>
				<div class="nameandemail">
					<li class="fields formli">
						<label for="name" class="required lilabel"><em>*</em><?php echo Mage::helper('avejanarms')->__('Name') ?></label>
						<div class="input-box">
							<input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('avejanarms')->__('Name')) ?>" value="" class="input-text required-entry" type="text" />
						</div>
					</li>
					<li class="field formli">
						<label for="email" class="required lilabel"><em>*</em><?php echo Mage::helper('avejanarms')->__('Email') ?></label>
						<div class="input-box">
							<input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('avejanarms')->__('Email')) ?>" value="" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
						</div>
					 </li>
				</div>
			<?php }?>
			
            <li class="wide formli">
                <label for="question" class="required lilabel"><em>*</em><?php echo Mage::helper('avejanarms')->__('Question') ?></label>
                <div class="input-box">
                    <textarea name="question" id="question" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('avejanarms')->__('Question')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('avejanarms')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('avejanarms')->__('Submit') ?></span></span></button>
    </div>
</form>
</div>
	<div id="product-q-a">
		
	</div>
<script type="text/javascript">
//<![CDATA[
	
    var ravejanaeview = new VarienForm('avejanaqa', true);
//]]>
	jQuery('.qaformarea').css("display","none");
	jQuery( ".qatitle" ).click(function() {
	   jQuery('.qaformarea').toggle();
	});
	
	jQuery(document).ready(function(){
		var productid	= "<?php echo $current_product->getId();?>";
		setTimeout(function(){
		jQuery.ajax({
			url: "<?php echo $this->getUrl('avejanarms/qa/qaload');?>",
			type: "post",
			data: {'productid':productid} ,
			success: function (response) {
				jQuery('#product-q-a').html(response);
			  
			},
			error: function(jqXHR, textStatus, errorThrown) {
			   console.log(textStatus, errorThrown);
			}
		 });
		}, 200);
		console.log(productid);
		
	});
</script>
