<a id="review-tab-open" name="review-form"></a>
<?php 
		$avgrating 			=	0;
		$totalreview 		=	0;
		$current_product 	= 	Mage::registry('current_product');
 		$totalreview		=	$current_product->getAvejanaTotalreview();
		$avgrating			=	$current_product->getAvejanaAveragerating();
		$is_logo_show			=	Mage::getStoreConfig('avejanasetting/avejanaconfiguration/isshowlogo');
		$is_rich_snippet_show	=	Mage::getStoreConfig('avejanasetting/avejanaconfiguration/showrichsnippet');
		//echo $userurl	=	Mage::helper('avejanarms')->getUsersnurl();
		
		if($is_rich_snippet_show==1){
			echo $this->getLayout()->createBlock('avejanarms/catalog_product_view_markup')->setTemplate('avejanarms/catalog/product/view/markup.phtml')->toHtml();
		}
		
		if($is_logo_show==1){
			$showlogo_position 	= 	Mage::getStoreConfig('avejanasetting/avejanaconfiguration/logoposition');
			$reivew_logo_url 	= 	Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'Avejana/avejana-new-logo.png';	
		}
		

?>		
<div class="avejanarms">
	
	<?php if($is_logo_show==1){?>
		<div class="avejana-review-reply aveja-logo-holder <?php echo $showlogo_position; ?>">
			<div class="avejana_link" ><a target="_blank" href="https://avejana.com/"><?php echo Mage::helper('avejanarms')->__('Powered By');?></a></div><div class="awejana-logo" ><a target="_blank" href="https://avejana.com/"><img src="<?php echo $reivew_logo_url; ?>" height="21px" alt="" class="avejana-logo"></a></div>
		</div>
	<?php } ?>
	<div class="avejana_review_section">
		<div class="av-page-title avejanatitle">
			<a class="review_form_display" href="javascript:void(0)"><?php echo Mage::helper('avejanarms')->__('Write a Review') ?></a>

			<?php 
				  if($totalreview>0){
			?>
					<div class="pull-right"> 
						<span class="review-total"><strong style="line-height: 30px;"><?php echo $totalreview.' '.Mage::helper('avejanarms')->__('review(s)');?></strong></span>

						 <div class="stars star-ratings-sprite">
							 <span style="width:<?php echo $avgrating; ?>%" class="star-ratings-sprite-rating"></span>
						 </div>
					</div>

			<?php 	}?>

		</div>
		<div class="avejanareviewform avejana-content">
			<form action="<?php echo $this->getUrl('avejanarms/index/reviewpost'); ?>" id="av_ravejanaeview" method="post" class="scaffold-form">
				<div class="fieldarea">
					<input type="hidden" name="product_id" value="<?php echo $current_product->getId();?>"/> 
					<ul class="av-form-list">
						<li class="avratings">
							<label for="name" class="required ratingli lilabel"><em>*</em><?php echo Mage::helper('avejanarms')->__('Your Rating') ?></label>

								<span class="starRating">
									<input id="rating5" type="radio" name="rating" value="5">
									<label for="rating5">5</label>
									<input id="rating4" type="radio" name="rating" value="4">
									<label for="rating4">4</label>
									<input id="rating3" type="radio" name="rating" value="3" >
									<label for="rating3">3</label>
									<input id="rating2" type="radio" name="rating" value="2">
									<label for="rating2">2</label>
									<input id="rating1" type="radio" name="rating" value="1">
									<label for="rating1">1</label>
							   </span>

						</li>
						<li class="formli">
							<label for="name" class="lilabel required"><em>*</em><?php echo Mage::helper('avejanarms')->__('Title') ?></label>
							<div class="input-box">
								<input name="title" id="title" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('avejanarms')->__('Title')) ?>" value="" class="input-text required-entry validate-length maximum-length-100" maxlength="100" type="text" />
							</div>
						</li>

						<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) {

							// Load the customer's data
							$customer = Mage::getSingleton('customer/session')->getCustomer();
							echo '<input name="name" id="name" value="'.$customer->getName().'" class="input-text required-entry" type="hidden" />';

							echo '<input name="email" id="email" value="'.$customer->getEmail().'" class="input-text required-entry validate-email" type="hidden"  />';


						}else{ ?>


							<li class="fields formli">
								<label for="name" class="lilabel required"><em>*</em><?php echo Mage::helper('avejanarms')->__('Name') ?></label>
								<div class="input-box">
									<input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('avejanarms')->__('Name')) ?>" value="" class="input-text required-entry" type="text" />
								</div>
							</li>
							<li class="field formli">
								<label for="email" class="lilabel required"><em>*</em><?php echo Mage::helper('avejanarms')->__('Email') ?></label>
								<div class="input-box">
									<input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('avejanarms')->__('Email')) ?>" value="" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
								</div>
							 </li>

						<?php } ?>

						<li class="wide formli">
							<label for="comment" class="lilabel required"><em>*</em><?php echo Mage::helper('avejanarms')->__('Review') ?></label>
							<div class="input-box">
								<textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('avejanarms')->__('Review')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
							</div>
						</li>
					</ul>

				</div>
				<div class="buttons-set">
					<input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
					<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('avejanarms')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('avejanarms')->__('Submit') ?></span></span></button>
				</div>
			</form>
		</div>

		 <div id="avejana-review-reply" class="avejana-review-reply">
			
		</div>
	</div>
</div>
<script type="text/javascript">

   var av_ravejanaeview = new VarienForm('av_ravejanaeview', true);
	jQuery(this).scrollTop(0);
	jQuery('.avejanareviewform').css("display","none");
	jQuery( ".review_form_display" ).click(function() {
	   jQuery('.avejanareviewform').toggle();
	});
	
	jQuery(document).ready(function(){
		jQuery('html,body').animate({scrollTop:0},0);
		var productid= "<?php echo $current_product->getId();?>";
		setTimeout(function(){
		jQuery.ajax({
			url: "<?php echo $this->getUrl('avejanarms/index/reviewload');?>",
			type: "post",
			data: {'productid':productid} ,
			success: function (response) {
				jQuery('#avejana-review-reply').html(response);
			  	
			},
			error: function(jqXHR, textStatus, errorThrown) {
			   console.log(textStatus, errorThrown);
			}
		 });
			
		var apihit="<?php echo Mage::helper('avejanarms')->getPageView($current_product->getId());?>";
			console.log(apihit);
		}, 200);
		
		
	});
</script>
