<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="/skin/frontend/base/default/css/reviewandqa/bootstrap.min.css" >
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<?php 
$_items = $this->getReviewsCollection()->getItems();

 $reviewCount = $this->getReviewsCollection()->getSize();
$avejana_items = $this->getAvejanaReviewsCollection();
$mage_items = Mage::getSingleton('core/session')->getAvejanaTotalReviews();
$showlogo_position = '';
$avejana_review_data = array();
$AvejanaRating = 0; 
$avejana_items_cnt = 0;
foreach($avejana_items as $k => $avejana_review){ 
	$key = (string)$k;
	if( $key != 'pid'){
			$ReviewID = $avejana_review->ReviewID;	
			$avejana_review_array = (array)	$avejana_review;	
			$avejana_review_data[$ReviewID] = $avejana_review_array;		
			$AvejanaRating += (int)$avejana_review->Ratings;
			$avejana_items_cnt++;
	}
}

$avejanaAvgRating =  $AvejanaRating / $reviewCount;
?>
<?php if ($this->getLogoStatus() == '1') {
$showlogo_position = Mage::getStoreConfig('tabssection/general/where_is_show_logo');
$reivew_logo_url = Mage::getBaseUrl().'media/Avejana/avejana-new-logo.png';	
?>		
<div class="avejana-review-reply aveja-logo-holder <?php echo $showlogo_position; ?>">
	<div class="avejana_link" ><a target="_blank" href="https://avejana.com/">Powered By</a></div><div class="awejana-logo" ><a target="_blank" href="https://avejana.com/"><img src="<?php echo $reivew_logo_url; ?>" height="21px" alt="" class="avejana-logo"></a></div>
</div>
<?php } ?>
<div class="box-collateral box-reviews <?php echo $showlogo_position; ?>  row" id="customer-reviews">
	<!--<div class="review_header_div" ><h4><?php echo $this->__('Customer Reviews') ?></h4></div>-->
	<?php //if($mage_items <= 0):?>
	<?php if( !$mage_items ) { ?>
			<div class="col-sm-4 col-md-4 col-xs-12 ipad-btn" >
			<button id="avejana_review_from" class="pull-left btn btn-primary" style="margin-bottom:10px; background-color: #808080; border-color: #808080; display: block;" type="button"><i class="fa fa-paste"></i> Be the First to Review</button>
		</div>
		
	<?php }else{ ?>

		<div class="col-sm-4 col-md-4 col-xs-12 ipad-btn">
			<button id="avejana_review_from" class="pull-left btn btn-primary" style="background-color: #808080; border-color: #808080; display: block;" type="button"><i class="fa fa-paste"></i> Write Review</button>
		</div>
		
		<div class="col-sm-8 col-md-8 col-xs-12 pad-0 big-star">
			
			<div class="pull-right">
				<span class="review-total"><div class="col-sm-12 col-md-12 col-xs-12 pad-0 reviews-count-left"><strong style="line-height: 25px;"><?php echo $reviewCount; ?> review(s)</strong>
					<input type="text" class="top-star rating rating-loading" value="<?php echo round($avejanaAvgRating); ?>" data-size="xs" title="" readonly=""></div>
				</span>
				<?php if($reviewCount >= 5){ ?>
				<div class="avejana-pager"><?php echo $this->getPagerHtml(); ?></div>
				<?php } ?>
			</div>
		</div>

 	<?php } ?>
	  
	<div class="review-forms row">
		<?php echo $this->getLayout()->createBlock('reviewandqa/form')->setBlockId('product.review.form')->toHtml() ?>
	</div>
	
	<?php if( $mage_items ) { ?>
	<div class="avejana-review-reply">
		<?php 			foreach($_items as $_review):						
						//echo "<pre>";print_r($_review);exit;
						$review_id = $_review->getId();
						$avejana_review = $avejana_review_data[$review_id];
						$first_letter = substr($_review->getNickname(), 0 , 1);
						?>
						<div style="width: 97%; margin: 0 15px;"><hr style="width: 100%;"></div>
							<div class="avejana-review-feld">
								<div class="avejana-initial" style="text-align: center; position: relative; margin-top: 15px;">
									<a href="javascript:void(0)">
										<span class="first-letter" style="font-size: 40px; text-align: center; background-color: #888888; padding-left: 10px; padding-right: 10px; color: #FFFFFF"><?php echo ucfirst($first_letter); ?></span>
									</a>
								</div>
								<div class="avejana-feed"><div class="avejana-initial" style="position: relative; ">
									<strong><a href="javascript:void(0)" class="text-muted"><?php echo $_review->getNickname(); ?></a></strong>&nbsp;<small class="text-muted"><?php echo $this->__('  %s', date_format($_review->getCreated_at(),"d.m.Y")) ?></small>
									<div class=" avejana-small-star">
										<div id="review_rate" class="display_rate avejana-container"  readonly="readonly">
											<?php 
												$_votes = $_review->getRatingVotes(); 
												if(count($_votes)): 
												foreach($_votes as $_vote): 
											?>
												
												<input type="text" class="rating rating-loading small" value="<?php echo $_vote->getValue() ?>" data-size="xs" title="" readonly="">
											<?php 
												endforeach;
												endif; 
											?>	
											<div class="avejana-five-star">
												<div class="avejana-sub-star avejana-five-star">
												</div>
											</div>
										</div>
									</div>
										<div style="margin-top: 1.5%"><a href="javascript:void(0)"><?php echo $_review->getTitle();?></a></div>
										<div class="avejana-tweet"><p style="color: #000000;"><?php echo $review_destails = nl2br($_review->getDetail()); ?></p></div>
								<?php if($avejana_review['Reply'] != ''){ ?>
        							<div class="avejana-responce"><p class="avejana-header"><i class="fa fa-comment"></i>&nbsp;<span><?php echo $avejana_review['RepliedBy']; ?></span> Response :</p>
							        <div class="response"><p class="detail"><?php echo $avejana_review['Reply']; ?></p></div>
							        </div>
								<?php } ?>
		</div></div></div>
						<!--<div class="avejana-review">
							<div class="review-section">
								<div class="review-info">
									<span class="reviewer"><?php echo $_review->getNickname(); ?></span>
									<span class="post-date date"><?php echo $this->__('  %s', date_format($date,"d.m.Y")) ?></span>
								</div>
								<?php 
								$_votes = $_review->getRatingVotes(); 
								if(count($_votes)): 
								foreach($_votes as $_vote): 
								?>
								<div class="ratings-table">
									<div class="rating-box">
										<div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
									</div>
								</div>
								<input type="text" class="rating rating-loading small" value="'.$rating.'" data-size="xs" title="" readonly="">
								<?php 
								endforeach;
								endif; 
								?>	
								<div class="rview-title ref-link" ><a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><?php echo $_review->getTitle();?></a></div>
								<div class="review-descripition">
									<p class="detail"><?php echo $review_destails = nl2br($_review->getDetail()); ?></p>
								</div>
							</div>							<?php 																					if($avejana_review['Reply'] != ''){ ?>
							<div class="avejana-response">
								<p class="avejana-header"><span class="responsed-by"><?php echo $avejana_review['RepliedBy']; ?></span> Response : </p>								<?php echo $avejana_review['Reply']; ?>
							</div> 							<?php } ?>
						</div>-->
						
						<?php
		endforeach; 
		?>
	</div>
	<?php } ?>
	<a name="review2-form"></a>
	
</div>
<script>
jQuery( document ).ready(function() {
   jQuery('.wpc_comment_tab_tab a').attr('id','avejana_questions_tab');
   
   jQuery( "#avejana_review_from" ).click(function() {
	   jQuery('#Awejana_review_form').toggle();
	});
	
});
</script>
<script type="text/javascript">

	//<![CDATA[
	$('review-form').hide();
	$('add-review').observe('click', function(event){
			$('review-form').toggle();
		});
		
	var contactForm = new VarienForm('review-form', true);  
	jQuery(document).ready(function () { 
			
			var nullField = false;
			jQuery("#review-form :input").each(function(){
					if(jQuery(this).val() == ''){
						nullField = true;
					}
				});
			jQuery('#review-form > .buttons-set > button').click(function(e) {
					if(nullField == false){
						jQuery(this).disabled = true;
					}
				});
				
				
		});
	//]]>
</script>
   <?php 
   $page = Mage::app()->getRequest()->getParam('p');
   if ($page > 0 && $page != "") { ?>
   
		   <script type="text/javascript">
			//<![CDATA[
			
			jQuery(document).ready(function () { 
					
					jQuery(".extra-tabs li").each(function(){
						jQuery(this).removeClass('active');
						var tabid = jQuery(this).attr('id');
						jQuery('#'+tabid+'_contents').hide();
					});
					jQuery('#extra_tabs_reviews').addClass('active');
					jQuery('#extra_tabs_reviews_contents').show();
					
				});
			//]]>
		</script>
       
   <?php } ?>