<?php 
$_items = $this->getReviewsCollection()->getItems(); 
$avejana_items = $this->getAvejanaReviewsCollection();
$mage_items = Mage::getSingleton('core/session')->getAvejanaTotalReviews();
$showlogo_position = '';
$avejana_review_data = array();
$AvejanaRating = 0; 
$avejana_items_cnt = 0;
foreach($avejana_items as $k => $avejana_review){ 
	$key = (string)$k;
	if( $key != 'pid'){
			$ReviewID = $avejana_review->ReviewID;	
			$avejana_review_array = (array)	$avejana_review;	
			$avejana_review_data[$ReviewID] = $avejana_review_array;		
			$AvejanaRating += (int)$avejana_review->Ratings;
			$avejana_items_cnt++;
	}


}
$avejanaAvgRating = ( $AvejanaRating * 20 ) / $avejana_items_cnt;
?>

<?php if ($this->getLogoStatus() == '1') {
$showlogo_position = Mage::getStoreConfig('tabssection/general/where_is_show_logo');
$reivew_logo_url = Mage::getBaseUrl().'media/Avejana/avejana-new-logo.png';	
?>		
<div class="avejana-review-reply aveja-logo-holder <?php echo $showlogo_position; ?>">
	<div class="avejana_link" ><a target="_blank" href="https://avejana.com/">Powered By.</a></div><div class="awejana-logo" ><img src="<?php echo $reivew_logo_url; ?>" alt="" class="avejana-logo"></div>
</div>
<?php } ?>


<div class="box-collateral box-reviews <?php echo $showlogo_position; ?>" id="customer-reviews">
	<div class="review_header_div" ><h4><?php echo $this->__('Customer Reviews') ?></h4></div>
	<?php if($mage_items <= 0):?>
	<div class="avejana-review-top-links">
		<div class="review-form-link"><strong><a href="#review-form" id="add-review"><?php echo $this->__('Be the First to Review'); ?></a></strong></div>
	</div>
	<?php else: ?>	<div class="avejana-rating-summary avejana-rating-summary-right" >			<div class="avejana-review-count"><?php echo $mage_items.' Reviews ' ?></div>			<div class="ratings-table">				<div class="rating-box">					<div class="rating" style="width:<?php echo $avejanaAvgRating; ?>%;"></div>				</div>			</div>	</div> 
	<div class="avejana-review-top-links">	
		<div class="review-form-link"><strong><a href="#review-form" id="add-review"><?php echo $this->__('Write Review'); ?></a></strong></div>
		<div class="avejana-pager"><?php echo $this->getPagerHtml(); ?></div>	
	</div>
	
	<div class="avejana-review-reply">
		<?php 			foreach($_items as $_review):						
						
						$review_id = $_review->getId();
						$avejana_review = $avejana_review_data[$review_id];
						?>
						<div class="avejana-review">
							<div class="review-section">
								<div class="review-info">
									<span class="reviewer"><?php echo $_review->getNickname(); ?></span>
									<span class="post-date date"><?php echo $this->__('  %s', date_format($date,"d.m.Y")) ?></span>
								</div>
								<?php 
								$_votes = $_review->getRatingVotes(); 
								if(count($_votes)): 
								foreach($_votes as $_vote): 
								?>
								<div class="ratings-table">
									<div class="rating-box">
										<div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
									</div>
								</div>
								<?php 
								endforeach;
								endif; 
								?>	
								<div class="rview-title ref-link" ><a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><?php echo $_review->getTitle();?></a></div>
								<div class="review-descripition">
									<p class="detail"><?php echo $review_destails = nl2br($_review->getDetail()); ?></p>
								</div>
							</div>							<?php 																					if($avejana_review['Reply'] != ''){ ?>
							<div class="avejana-response">
								<p class="avejana-header"><span class="responsed-by"><?php echo $avejana_review['RepliedBy']; ?></span> Response : </p>								<?php echo $avejana_review['Reply']; ?>
							</div> 							<?php } ?>
						</div>
						<?php
		endforeach; 
		?>
	</div>
	<?php endif;?>
	<a name="review2-form"></a>
	<div class="review-forms">
		<?php echo $this->getLayout()->createBlock('reviewandqa/form')->setBlockId('product.review.form')->toHtml() ?>
	</div>
</div>

<script type="text/javascript">
	//<![CDATA[
	$('review-form').hide();
	$('add-review').observe('click', function(event){
			$('review-form').toggle();
		});
		
	var contactForm = new VarienForm('review-form', true);  

	jQuery(document).ready(function () { 
			
			var nullField = false;
			jQuery("#review-form :input").each(function(){
					if(jQuery(this).val() == ''){
						nullField = true;
					}
				});
			jQuery('#review-form > .buttons-set > button').click(function(e) {
					if(nullField == false){
						jQuery(this).disabled = true;
					}
				});
				
				
		});
	//]]>
</script>

   <?php 
   $page = Mage::app()->getRequest()->getParam('p');
   if ($page > 0 && $page != "") { ?>
   
		   <script type="text/javascript">
			//<![CDATA[
			
			jQuery(document).ready(function () { 
					
					jQuery(".extra-tabs li").each(function(){
						jQuery(this).removeClass('active');
						var tabid = jQuery(this).attr('id');
						jQuery('#'+tabid+'_contents').hide();
					});
					jQuery('#extra_tabs_reviews').addClass('active');
					jQuery('#extra_tabs_reviews_contents').show();
					
				});
			//]]>
		</script>
       
   <?php } ?>