
<?php if($this->getReviewsCount()): ?>
<div class="ratings">
	<?php if($this->getRatingSummary()):?>
	<div class="rating-box">
		<div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
	</div>
	<?php endif;?>
	<p class="rating-links">
		<a href="#extra_tabs_tab_review" id='review_summery_count'><?php echo $this->__('%d Review(s)', $this->getAvejanaReviewsCount()) ?></a>
		<!--<span class="separator">|</span>
		<a href="#review-form"><?php echo $this->__('Add Your Review') ?></a>-->
	</p>
</div>
<?php elseif($this->getDisplayIfEmpty()): ?>
<p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>
<!--<script>
	
	jQuery( "#review_summery_count" ).click(function(event) {
		jQuery( "#extra_tabs_tab_review > a" ).click();
	});
</script>-->